# Generated by Django 3.1.1 on 2020-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=150)),
                ('year', models.IntegerField(max_length=4)),
                ('language_code', models.CharField(max_length=10)),
                ('average_rating', models.DecimalField(max_digits=3, decimal_places=2)),
                ('ratings_count', models.IntegerField(max_length=13)),
                ('ratings_1', models.IntegerField(max_length=13)),
                ('ratings_2', models.IntegerField(max_length=13)),
                ('ratings_3', models.IntegerField(max_length=13)),
                ('ratings_4', models.IntegerField(max_length=13)),
                ('ratings_5', models.IntegerField(max_length=13)),
                ('publisher', models.CharField(max_length=150)),
                ('image_url', models.CharField(max_length=1024)),
                ('small_image_url', models.CharField(max_length=1024)),
            ],
        ),
    ]
