# Generated by Django 3.1.1 on 2020-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('year', models.IntegerField(max_length=4)),
                ('publisher', models.CharField(max_length=150)),
                ('imageurls', models.CharField(max_length=255)),
                ('imageurlm', models.CharField(max_length=255)),
                ('imageurll', models.CharField(max_length=255)),
            ],
        ),
    ]
