apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-database-persistent-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/aleksandarrajic/Documents/Projects/Elfak/Master/db/mysql/users
