apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-database-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
