version: '3'

services:
    api_gateway:
        build: ./APIGateway
        container_name: master_api_gateway
        restart: unless-stopped
        env_file: ./APIGateway/.env
        environment: 
            - BASE_URL_ARTEFACTS=http://artefacts_service:9002
            - BASE_URL_USERS=http://users_service:9000
            - BASE_URL_CLUSTERIZATION=http://clustering_engine:5000
        ports:
            - 9080:9080

    artefacts_service:
        build: ./artefacts_service
        container_name: master_artefacts_service
        restart: unless-stopped
        env_file: ./artefacts_service/.env
        ports:
            - 9002:9002

    users_service:
        build: ./users_service
        container_name: master_users_service
        restart: unless-stopped
        env_file: ./users_service/.env
        ports:
            - 9000:9000

    neural_network:
        build: ./python
        container_name: master_neural_network
        restart: always
        ports:
            - 5001:8000
        networks: 
            - masternet

    clustering_engine:
        build: ./clustering_engine
        container_name: master_clustering_engine
        restart: unless-stopped
        ports:
            - 5000:5000

networks: 
    masternet: