version: '3'

services:
    api:
        build: ./
        volumes:
            - ./api:/master-api
            - master-api/node_modules
        container_name: alx_master_api
        restart: unless-stopped
        env_file: ./api/.env
        ports:
            - 5000:5000
        command: "nodemon server.js"
        depends_on:
          - postgres_db
    email_service:
        build: ./email_service
        volumes:
            - ./email_service:/email-service
            - email-service/node_modules
        container_name: alx_email_service
        restart: unless-stopped
        env_file: ./email_service/.env
        ports:
            - 5002:5002
        command: "nodemon server.js"
        depends_on:
          - postgres_db
    postgres_db:
        image: postgres
        volumes:
            - master_psqldb:/var/lib/postgresql/data
        ports:
            - 5003:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=masterdb
            # - PG_
#    cache:
#        image: redis:latest
#        ports:
#            - 6379:6379
#    clustering_engine:
#        build:
#            context: ./clustering_engine
#            dockerfile: ./Dockerfile
#        image: alx_clustering-engine
#        container_name: alx_clustering_engine
#        restart: unless-stopped
#        env_file: ./clustering_engine/.env
#        command: /clustering-engine/node_modules/.bin/nodemon server.js
#        ports:
#            - 5001:5001
#        volumes:
#            - ./clustering_engine:/clustering-engine
#            - clustering-engine/node_modules

volumes:
    master_psqldb:
        external: true