version: '3'

services:
    api_gateway:
        build: ./APIGateway
        volumes:
            - ./APIGateway:/master-api_gateway
        container_name: master_api_gateway
        restart: unless-stopped
        env_file: ./APIGateway/.env
        ports:
            - 9080:3000

    artefacts_service:
        build: ./artefacts_service
        volumes:
            - ./artefacts_service:/master-artefacts_service
        container_name: master_artefacts_service
        restart: unless-stopped
        env_file: ./artefacts_service/.env
        ports:
            - 9002:9002

    users_service:
        build: ./users_service
        container_name: master_users_service
        restart: unless-stopped
        env_file: ./users_service/.env
        ports:
            - 9000:9000

    neural_network:
        build: ./python
        container_name: master_neural_network
        restart: always
        ports:
            - 5001:8000
        networks: 
            - masternet

volumes:
    master_psqldb:
        external: true

networks: 
    masternet: