apiVersion: v1
kind: Service
metadata:
  name: clustering-engine-service
spec:
  selector:
    app: clustering-engine
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
